{% set name = "napari-tiledb-bioimg" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tiledb-bioimg-{{ version }}.tar.gz
  sha256: 2ddf394d3f48832cca322c4649b73d7f6e43efc7752b9f8f69864ee2ae4c40d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - python >=3.8
    - napari
    - tiledb-bioimg >=0.2.1
    - tiledb-py              # Remove after dependency is fixed on tiledb-bioimg

test:
  imports:
    - napari_tiledb_bioimg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-tiledb-bioimg
  summary: Support reading and writing TileDB-Bioimaging image arrays within Napari
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/TileDB-Inc/napari-tiledb-bioimg

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - ktsitsi
    - Shelnutt2
